config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blogs

  # Main
  
  # Blog
  get 'blog/index'

  # Home
  get 'home/about'
  get 'home/contact'
  get 'home/journey'

  # Redirect Path
  # get '*path' => redirect('/') #// redirects to home page if the route is not found.

  # Devise
  get 'users/sign_in'
  get 'user/sign_up'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all.order("created_at DESC")
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def journey
  end

  def sign_in
  end

  def sign_out
  end

  def sign_up
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <% if blob.video? %>
    <%= video_tag url_for(blob.attachable),
    preload: "auto",
    controls: "controls",
    width: "640",
    height: "264" %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Title:</strong>
    <%= blog.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= blog.content %>
  </p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.rich_text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blogs</h1>

<div id="blogs">
  <% @blogs.each do |blog| %>
    <%= render blog %>
    <p>
      <%= link_to "Show this blog", blog %>
    </p>
  <% end %>
</div>

<% if user_signed_in? %>
  <%= link_to "New blog", new_blog_path %>  
  <% else %>
<% end %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<link href="https://vjs.zencdn.net/7.20.2/video-js.css" rel="stylesheet" />
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete %>
</div>
<script src="https://vjs.zencdn.net/7.20.2/video.min.js"></script>

app/views/home/_footer.html.erb
<div class="d-flex flex-direction-column justify-content-center align-items-center">© 2022 Copyright: Karl Kemister-Sheppard</div>

 <ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="nav-link bi bi-linkedin" href="https://www.linkedin.com/in/karl-kemister-sheppard-09b34889/"></a>
  </li>
  <li class="nav-item">
    <a class="nav-link bi bi-github" href="https://github.com/kemister85"></a>
  </li>
  <li class="nav-item">
    <a class="nav-link bi bi-telephone" href="tel:+61413431813"></a>
  </li>
  <li class="nav-item">
    <a class="nav-link bi bi-envelope" href="mailto:karlkemistersheppard@gmail.com"></a>
  </li>
</ul>

 <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <%= button_to "Log in", new_user_session_path, class:"btn btn-primary btn-sm"%>
          <% if user_signed_in? %> 
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class:"btn btn-danger btn-sm"%>
          <% end %>
        </div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <%= link_to 'KKS', root_path, class:"navbar-brand"%>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
      <% if user_signed_in? %> 
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact', home_contact_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Journey', blogs_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Create New Post', new_blog_path, class:"nav-link"%>
        </li>
        

      <% else %>
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact', home_contact_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Journey', blogs_path, class:"nav-link"%>
        </li>
      <% end %>
      </div>
    </div>
  </div>

</nav>

app/views/home/about.html.erb
<h1>About</h1>
    <h2>Passionate | Driven | Focused</h2>
<div>
Dedicated, task-driven professional with over 18 years of experience delivering business outcomes in FMCG sales and hospitality industries.<br> 
Equipped with an extensive library of knowledge and skills from my previous careers I am proficient in problem-solving, cost analysis, negotiations, strategic planning and creating development plans to improve both company and client objectives.<br> 

I display excellent verbal and written communication skills and have experience providing coaching and mentoring to support team members.<br> 
Other than coming pre-compiled with my previous array of experience, I have a basic understanding of design, wireframing and general coding practices <br> 
Technical skills include foundational programming experience with ROR | Ruby | CSS “SCSS” | HTML5 | Git “GitHub”.<br> 
<br> 

<h2>ADDITIONAL ATTRIBUTES AND QUALITIES</h2>
    <ul>
        <li>Positive work attitude and an eagerness to learn</li>
        <li>Able to work both autonomously and within a team</li>
        <li>Interact with clients to capture feedback and product issues</li>
        <li>Excellent verbal and written communication</li>
        <li>Strong stakeholder engagement and presentation skills</li>
        <li>Ability to work towards a deadline and manage multiple priorities</li>
        <li>Proactive and coupled with a passion for software development</li>
    </ul> 
</div>

<div>
    <h1>This is a test for About SCSS</h1>
</div>

app/views/home/contact.html.erb
<h1>Contact Page</h1>

<!--Section: Contact v.2-->
<section class="mb-4">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div class="row">

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form" action="mail.php" method="POST">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="name" name="name" class="form-control">
                            <label for="name" class="">Your name</label>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="email" name="email" class="form-control">
                            <label for="email" class="">Your email</label>
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <input type="text" id="subject" name="subject" class="form-control">
                            <label for="subject" class="">Subject</label>
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <input type="text" id="message" name="message" rows="2" class="form-control md-textarea">
                            <label for="message">Your message</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center text-md-left">
                <a class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
            </div>
            <div class="status"></div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>San Francisco, CA 94126, USA</p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>+ 01 234 567 89</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    <p>contact@mdbootstrap.com</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

    </div>

</section>
<!--Section: Contact v.2-->

app/views/home/index.html.erb
<p class="navbar-text float-right">
<% if user_signed_in? %>Logged in as 
<strong><%= current_user.email %></strong>.
<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
<%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> 

<% else %>
<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

<h1>Hi,<br>
I'm Karl,<br></h1>


<h4>
<div id="fragment1">Full Stack Developer</div>
<div id="fragment2">Techie Enthusiast</div>
</h4>


<p class="index-p">Husband, Father</p><br><br>

<div class="contact-link">
    <%= link_to 'Contact me!', home_contact_path, class:"btn btn-secondary btn-lg"%>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%# PrismJS Theme %>
    <link rel="stylesheet" href="http://prismjs.com/themes/prism-twilight.css"/>
    <script type='text/javascript' src="http://prismjs.com/prism.js"></script>
  </head>

  <body>
    <%# Notice Flash Messages %>
  	<% if notice %>
  	<p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= render "home/header"%>
    <%= yield %>
    <%= render "home/footer"%>

  </body>
  </body>
</html>